// This file was auto-generated by ML.NET Model Builder. 

using System;
using CovidBilgilendirmeML.Model;

namespace CovidBilgilendirmeML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                HealthWorker = @"Hay�r",
                MedicalCenter = @"Hay�r",
                Touch = @"Hay�r",
                Fever = @"D���k",
                ChronicLung = @"Hay�r",
                Diabetes = @"Hay�r",
                Hypertension = @"Hay�r",
                ChronicLiver = @"Hay�r",
                Chemotheraphy = @"Hay�r",
                FeverHour = @"Hay�r",
                ShortnesOfBreath = @"Hay�r",
                Sorethrout = @"Hay�r",
                RunnyNose = @"Hay�r",
                Diearrhea = @"Hay�r",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Class with predicted Class from sample data...\n\n");
            Console.WriteLine($"HealthWorker: {sampleData.HealthWorker}");
            Console.WriteLine($"MedicalCenter: {sampleData.MedicalCenter}");
            Console.WriteLine($"Touch: {sampleData.Touch}");
            Console.WriteLine($"Fever: {sampleData.Fever}");
            Console.WriteLine($"ChronicLung: {sampleData.ChronicLung}");
            Console.WriteLine($"Diabetes: {sampleData.Diabetes}");
            Console.WriteLine($"Hypertension: {sampleData.Hypertension}");
            Console.WriteLine($"ChronicLiver: {sampleData.ChronicLiver}");
            Console.WriteLine($"Chemotheraphy: {sampleData.Chemotheraphy}");
            Console.WriteLine($"FeverHour: {sampleData.FeverHour}");
            Console.WriteLine($"ShortnesOfBreath: {sampleData.ShortnesOfBreath}");
            Console.WriteLine($"Sorethrout: {sampleData.Sorethrout}");
            Console.WriteLine($"RunnyNose: {sampleData.RunnyNose}");
            Console.WriteLine($"Diearrhea: {sampleData.Diearrhea}");
            Console.WriteLine($"\n\nPredicted Class value {predictionResult.Prediction} \nPredicted Class scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
